/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Feb 11, 2011, 9:56:00 PM
 */
package autotrade.gui;

import javax.swing.JSpinner;
import javax.swing.JTextField;
import autotrade.core.*;
import autotrade.core.database.AutoTradeDatabaseManagement;
import autotrade.gui.panel.NewUserPanel;
import java.awt.Color;
import java.sql.*;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JDialog;
import org.jfree.data.xy.*;
import org.jfree.chart.*;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.labels.StandardXYToolTipGenerator;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.StandardXYBarPainter;
import org.jfree.chart.renderer.xy.XYBarRenderer;
import org.jfree.chart.renderer.xy.XYItemRenderer;
import org.jfree.data.time.TimeSeries;
import org.jfree.data.time.TimeSeriesCollection;

/**
 *
 * @author Dinh
 */
public class MainFrame extends javax.swing.JFrame {

    private static final long ONE_DAY = 86400000; //milisecond

    public static JDialog datatypeDialog;

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJTabbedPane = new javax.swing.JTabbedPane();
        managementJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        newJButton = new javax.swing.JButton();
        removeJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        transactionJPanel = new javax.swing.JPanel();
        chartJPanel = new javax.swing.JPanel();
        symbolJLabel = new javax.swing.JLabel();
        symbolJComboBox = new javax.swing.JComboBox();
        openPriceJLabel = new javax.swing.JLabel();
        openPriceJTextField = new javax.swing.JTextField();
        highPriceJLabel = new javax.swing.JLabel();
        highPriceJTextField = new javax.swing.JTextField();
        lowPriceJLabel = new javax.swing.JLabel();
        lowPriceJTextField = new javax.swing.JTextField();
        closePriceJLabel = new javax.swing.JLabel();
        closePriceJTextField = new javax.swing.JTextField();
        volumeJLabel = new javax.swing.JLabel();
        volumeJTextField = new javax.swing.JTextField();
        final XYDataset priceDataset = createPriceDataset(AutoTradeLocalData.load().getCurrentDate(),AutoTradeLocalData.load().getCurrentDate(), null, "close");
        final XYDataset volumeDataset = createVolumeDataset(AutoTradeLocalData.load().getCurrentDate(),AutoTradeLocalData.load().getCurrentDate(), null);
        final JFreeChart chart = createPriceVolumeChart(priceDataset, volumeDataset);
        priceVolumeChartJPanel = new ChartPanel(chart);
        priceTypeJLabel = new javax.swing.JLabel();
        priceTypeJComboBox = new javax.swing.JComboBox();
        numberOfDayJLabel = new javax.swing.JLabel();
        numberOfDayJSpinner = new javax.swing.JSpinner();
        AccountInfoJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        userJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        dateJPanel = new javax.swing.JPanel();
        dateJLabel = new javax.swing.JLabel();
        dateJSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("List of existing Users");

        newJButton.setText("New");
        newJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newJButtonActionPerformed(evt);
            }
        });

        removeJButton.setText("Remove");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "User Name", "User Type", "Technical Analysis Method", "Cash Remain"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(35);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(25);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(20);

        jButton1.setText("Refresh");

        javax.swing.GroupLayout managementJPanelLayout = new javax.swing.GroupLayout(managementJPanel);
        managementJPanel.setLayout(managementJPanelLayout);
        managementJPanelLayout.setHorizontalGroup(
            managementJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managementJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(managementJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(managementJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(removeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addContainerGap())
        );
        managementJPanelLayout.setVerticalGroup(
            managementJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managementJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(managementJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(managementJPanelLayout.createSequentialGroup()
                        .addComponent(newJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        mainJTabbedPane.addTab("Management", managementJPanel);

        symbolJLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        symbolJLabel.setText("Symbol:");

        symbolJComboBox.setEditable(true);
        symbolJComboBox.setModel(new javax.swing.DefaultComboBoxModel(AutoTradeInfo.LIST_ALL_JSC_SYMBOL.toArray()));
        JTextField field = (JTextField)symbolJComboBox.getEditor().getEditorComponent();
        field.setText("");
        field.addKeyListener(new ComboKeyHandler(symbolJComboBox));
        symbolJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symbolJComboBoxActionPerformed(evt);
            }
        });

        openPriceJLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        openPriceJLabel.setText("Open:");

        openPriceJTextField.setEditable(false);
        openPriceJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        highPriceJLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        highPriceJLabel.setText("High:");

        highPriceJTextField.setEditable(false);
        highPriceJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lowPriceJLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        lowPriceJLabel.setText("Low:");

        lowPriceJTextField.setEditable(false);
        lowPriceJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        closePriceJLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        closePriceJLabel.setText("Close:");

        closePriceJTextField.setEditable(false);
        closePriceJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        volumeJLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        volumeJLabel.setText("Volume:");

        volumeJTextField.setEditable(false);
        volumeJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout priceVolumeChartJPanelLayout = new javax.swing.GroupLayout(priceVolumeChartJPanel);
        priceVolumeChartJPanel.setLayout(priceVolumeChartJPanelLayout);
        priceVolumeChartJPanelLayout.setHorizontalGroup(
            priceVolumeChartJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        priceVolumeChartJPanelLayout.setVerticalGroup(
            priceVolumeChartJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );

        priceTypeJLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        priceTypeJLabel.setText("Price Type:");

        priceTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Open", "High", "Low", "Close" }));
        priceTypeJComboBox.setSelectedIndex(3);
        priceTypeJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTypeJComboBoxActionPerformed(evt);
            }
        });

        numberOfDayJLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        numberOfDayJLabel.setText("Number of day:");

        numberOfDayJSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(300), Integer.valueOf(0), null, Integer.valueOf(1)));
        numberOfDayJSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numberOfDayJSpinnerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout chartJPanelLayout = new javax.swing.GroupLayout(chartJPanel);
        chartJPanel.setLayout(chartJPanelLayout);
        chartJPanelLayout.setHorizontalGroup(
            chartJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chartJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(symbolJLabel)
                    .addComponent(priceTypeJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chartJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(symbolJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTypeJComboBox, 0, 83, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chartJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chartJPanelLayout.createSequentialGroup()
                        .addComponent(openPriceJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openPriceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(highPriceJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(highPriceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lowPriceJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lowPriceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(closePriceJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closePriceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(volumeJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(volumeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(chartJPanelLayout.createSequentialGroup()
                        .addComponent(numberOfDayJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberOfDayJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(priceVolumeChartJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        chartJPanelLayout.setVerticalGroup(
            chartJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chartJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(symbolJLabel)
                    .addComponent(openPriceJLabel)
                    .addComponent(openPriceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(highPriceJLabel)
                    .addComponent(highPriceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lowPriceJLabel)
                    .addComponent(lowPriceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closePriceJLabel)
                    .addComponent(closePriceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volumeJLabel)
                    .addComponent(volumeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(symbolJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chartJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOfDayJLabel)
                    .addComponent(numberOfDayJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTypeJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceVolumeChartJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("User");

        userJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Cash Remain");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel5.setText("x1000 VND");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("User Portfolio");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Symbol", "Volume", "Buy Price", "Current Price", "Gain/Loss"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setText("Gain/Loss");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setText("Buy stocks");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel10.setText("Sell stocks");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Symbol", "Price", "Volume", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Long.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Symbol", "Price", "Volume", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Long.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable5);

        javax.swing.GroupLayout AccountInfoJPanelLayout = new javax.swing.GroupLayout(AccountInfoJPanel);
        AccountInfoJPanel.setLayout(AccountInfoJPanelLayout);
        AccountInfoJPanelLayout.setHorizontalGroup(
            AccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccountInfoJPanelLayout.createSequentialGroup()
                .addGroup(AccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AccountInfoJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AccountInfoJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AccountInfoJPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(AccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                            .addGroup(AccountInfoJPanelLayout.createSequentialGroup()
                                .addGroup(AccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(AccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccountInfoJPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                            .addGroup(AccountInfoJPanelLayout.createSequentialGroup()
                                .addGroup(AccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 338, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        AccountInfoJPanelLayout.setVerticalGroup(
            AccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountInfoJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AccountInfoJPanelLayout.createSequentialGroup()
                        .addGroup(AccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(userJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(AccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(AccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
        );

        dateJLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        dateJLabel.setText("Date:");

        dateJSpinner.setModel(new javax.swing.SpinnerDateModel(AutoTradeLocalData.load().getCurrentDate(), null, null, Calendar.DAY_OF_MONTH));
        dateJSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dateJSpinner.setEditor(new JSpinner.DateEditor(dateJSpinner, "MM/dd/yyyy"));
        dateJSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dateJSpinnerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout dateJPanelLayout = new javax.swing.GroupLayout(dateJPanel);
        dateJPanel.setLayout(dateJPanelLayout);
        dateJPanelLayout.setHorizontalGroup(
            dateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dateJPanelLayout.createSequentialGroup()
                .addContainerGap(1012, Short.MAX_VALUE)
                .addComponent(dateJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dateJPanelLayout.setVerticalGroup(
            dateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(dateJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dateJLabel))
        );

        javax.swing.GroupLayout transactionJPanelLayout = new javax.swing.GroupLayout(transactionJPanel);
        transactionJPanel.setLayout(transactionJPanelLayout);
        transactionJPanelLayout.setHorizontalGroup(
            transactionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionJPanelLayout.createSequentialGroup()
                .addComponent(AccountInfoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chartJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(dateJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        transactionJPanelLayout.setVerticalGroup(
            transactionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionJPanelLayout.createSequentialGroup()
                .addComponent(dateJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transactionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccountInfoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chartJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mainJTabbedPane.addTab("Transaction", transactionJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateJSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dateJSpinnerStateChanged
        java.sql.Date currentDate = new java.sql.Date(((Date) dateJSpinner.getValue()).getTime());
        String symbol = (String) symbolJComboBox.getSelectedItem();

//        ArrayList<String> listJSCSymbol = AutoTradeInfo.getAllJSCSymbolAtThisTime(current_date);
//        symbolJComboBox.setModel(new javax.swing.DefaultComboBoxModel(listJSCSymbol.toArray()));
//        symbolJComboBox.setSelectedItem(symbol);

        AutoTradeLocalData.load().getCurrentDate().setTime(currentDate.getTime());
        updatePriceAndVolume(currentDate);

        Integer time = (Integer) numberOfDayJSpinner.getValue();
        java.sql.Date startDate = new java.sql.Date(currentDate.getTime() - ONE_DAY * time.longValue());
        final XYDataset priceDataset = createPriceDataset(startDate, currentDate, symbol, (String) priceTypeJComboBox.getSelectedItem());
        final XYDataset volumeDataset = createVolumeDataset(startDate, currentDate, symbol);
        final JFreeChart chart = createPriceVolumeChart(priceDataset, volumeDataset);
        ((ChartPanel) priceVolumeChartJPanel).setChart(chart);

    }//GEN-LAST:event_dateJSpinnerStateChanged

    private void numberOfDayJSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numberOfDayJSpinnerStateChanged
        java.sql.Date currentDate = new java.sql.Date(((Date) dateJSpinner.getValue()).getTime());
        String symbol = (String) symbolJComboBox.getSelectedItem();

        Integer time = (Integer) numberOfDayJSpinner.getValue();
        java.sql.Date startDate = new java.sql.Date(currentDate.getTime() - ONE_DAY * time.longValue());
        final XYDataset priceDataset = createPriceDataset(startDate, currentDate, symbol, (String) priceTypeJComboBox.getSelectedItem());
        final XYDataset volumeDataset = createVolumeDataset(startDate, currentDate, symbol);
        final JFreeChart chart = createPriceVolumeChart(priceDataset, volumeDataset);
        ((ChartPanel) priceVolumeChartJPanel).setChart(chart);
    }//GEN-LAST:event_numberOfDayJSpinnerStateChanged

    private void newJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newJButtonActionPerformed
        datatypeDialog = new JDialog();
        NewUserPanel panel = new NewUserPanel();
        datatypeDialog.add(panel);
        datatypeDialog.pack();
        datatypeDialog.setVisible(true);
    }//GEN-LAST:event_newJButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        AutoTradeLocalData.load().saveAutoTradeLocalData();
    }//GEN-LAST:event_formWindowClosing

    private void symbolJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symbolJComboBoxActionPerformed
        java.sql.Date currentDate = new java.sql.Date(((Date) dateJSpinner.getValue()).getTime());
        String symbol = (String) symbolJComboBox.getSelectedItem();
        
        updatePriceAndVolume(currentDate);

        Integer time = (Integer) numberOfDayJSpinner.getValue();
        java.sql.Date startDate = new java.sql.Date(currentDate.getTime() - ONE_DAY * time.longValue());
        final XYDataset priceDataset = createPriceDataset(startDate, currentDate, symbol, (String) priceTypeJComboBox.getSelectedItem());
        final XYDataset volumeDataset = createVolumeDataset(startDate, currentDate, symbol);
        final JFreeChart chart = createPriceVolumeChart(priceDataset, volumeDataset);
        ((ChartPanel) priceVolumeChartJPanel).setChart(chart);
    }//GEN-LAST:event_symbolJComboBoxActionPerformed

    private void priceTypeJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTypeJComboBoxActionPerformed
        java.sql.Date currentDate = new java.sql.Date(((Date) dateJSpinner.getValue()).getTime());
        String symbol = (String) symbolJComboBox.getSelectedItem();

        Integer time = (Integer) numberOfDayJSpinner.getValue();
        java.sql.Date startDate = new java.sql.Date(currentDate.getTime() - ONE_DAY * time.longValue());
        final XYDataset priceDataset = createPriceDataset(startDate, currentDate, symbol, (String) priceTypeJComboBox.getSelectedItem());
        final XYDataset volumeDataset = createVolumeDataset(startDate, currentDate, symbol);
        final JFreeChart chart = createPriceVolumeChart(priceDataset, volumeDataset);
        ((ChartPanel) priceVolumeChartJPanel).setChart(chart);
    }//GEN-LAST:event_priceTypeJComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountInfoJPanel;
    private javax.swing.JPanel chartJPanel;
    private javax.swing.JLabel closePriceJLabel;
    private javax.swing.JTextField closePriceJTextField;
    private javax.swing.JLabel dateJLabel;
    private javax.swing.JPanel dateJPanel;
    private javax.swing.JSpinner dateJSpinner;
    private javax.swing.JLabel highPriceJLabel;
    private javax.swing.JTextField highPriceJTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable5;
    private javax.swing.JLabel lowPriceJLabel;
    private javax.swing.JTextField lowPriceJTextField;
    private javax.swing.JTabbedPane mainJTabbedPane;
    private javax.swing.JPanel managementJPanel;
    private javax.swing.JButton newJButton;
    private javax.swing.JLabel numberOfDayJLabel;
    private javax.swing.JSpinner numberOfDayJSpinner;
    private javax.swing.JLabel openPriceJLabel;
    private javax.swing.JTextField openPriceJTextField;
    private javax.swing.JComboBox priceTypeJComboBox;
    private javax.swing.JLabel priceTypeJLabel;
    private javax.swing.JPanel priceVolumeChartJPanel;
    private javax.swing.JButton removeJButton;
    private javax.swing.JComboBox symbolJComboBox;
    private javax.swing.JLabel symbolJLabel;
    private javax.swing.JPanel transactionJPanel;
    private javax.swing.JComboBox userJComboBox;
    private javax.swing.JLabel volumeJLabel;
    private javax.swing.JTextField volumeJTextField;
    // End of variables declaration//GEN-END:variables

    private void updatePriceAndVolume(java.sql.Date current_date) {
        try {
            Connection conn = AutoTradeDatabaseManagement.getConnectionWithDatabase();
            Statement statement = conn.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * "
                    + "FROM stock_price_daily "
                    + "WHERE date LIKE '" + current_date.toString() + "' "
                    + "AND symbol LIKE '" + (String) symbolJComboBox.getSelectedItem() + "'");
            while (resultSet.next()) {
                Double open = resultSet.getDouble("open");
                Double high = resultSet.getDouble("high");
                Double low = resultSet.getDouble("low");
                Double close = resultSet.getDouble("close");
                Integer volume = resultSet.getInt("volume");

                openPriceJTextField.setText(open.toString());
                highPriceJTextField.setText(high.toString());
                lowPriceJTextField.setText(low.toString());
                closePriceJTextField.setText(close.toString());
                volumeJTextField.setText(volume.toString());
            }
            conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private XYDataset createPriceDataset(Date startDate, Date currentDate, String symbol, String priceType) {
        final TimeSeries priceSeries = AutoTradeInfo.getPriceSeries(startDate.getTime(), currentDate.getTime(), symbol, priceType);
        final TimeSeriesCollection dataset = new TimeSeriesCollection();
        dataset.addSeries(priceSeries);
        return dataset;
    }

    private XYDataset createVolumeDataset(Date startDate, Date currentDate, String symbol) {
        final TimeSeries volumeSeries = AutoTradeInfo.getVolumeSeries(startDate.getTime(), currentDate.getTime(), symbol);
        final TimeSeriesCollection dataset = new TimeSeriesCollection();
        dataset.addSeries(volumeSeries);
        return dataset;
    }

    private JFreeChart createPriceVolumeChart(final XYDataset priceDataset, final XYDataset volumeDataset) {
        JFreeChart chart = ChartFactory.createTimeSeriesChart(
                "",
                "Date",
                "Price",
                priceDataset,
                true,
                true,
                false);
        //chart.getXYPlot().getRangeAxis().setLowerBound(0);
        chart.setBackgroundPaint(Color.white);
        XYPlot plot = chart.getXYPlot();

        NumberAxis priceRangeAxis = (NumberAxis) plot.getRangeAxis();
        priceRangeAxis.setLowerMargin(0.40); // to leave room for volume bars
        DecimalFormat format = new DecimalFormat("00.00");
        priceRangeAxis.setNumberFormatOverride(format);

        XYItemRenderer priceRenderer = plot.getRenderer();
        priceRenderer.setBaseToolTipGenerator(
                new StandardXYToolTipGenerator(
                StandardXYToolTipGenerator.DEFAULT_TOOL_TIP_FORMAT,
                new SimpleDateFormat("d-MMM-yyyy"), new DecimalFormat("0.00")));

        NumberAxis volumeRangeAxis = new NumberAxis("Volume");
        volumeRangeAxis.setUpperMargin(1.00); // to leave room for price line
        plot.setRangeAxis(1, volumeRangeAxis);
        plot.setDataset(1, new XYBarDataset(volumeDataset, 100000000));
        plot.mapDatasetToRangeAxis(1, 1);
        XYBarRenderer volumeRenderer = new XYBarRenderer(0.20);
        volumeRenderer.setBarPainter(new StandardXYBarPainter());
        volumeRenderer.setShadowVisible(false);
        volumeRenderer.setBaseToolTipGenerator(
                new StandardXYToolTipGenerator(
                StandardXYToolTipGenerator.DEFAULT_TOOL_TIP_FORMAT,
                new SimpleDateFormat("d-MMM-yyyy"), new DecimalFormat("0,000.00")));
        volumeRenderer.setSeriesPaint(0, Color.GREEN);
        plot.setRenderer(1, volumeRenderer);
        return chart;
    }
}
