/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainJFrame.java
 *
 * Created on Jun 8, 2011, 10:46:54 AM
 */

package presentation;

import presentation.guiForDataUpdate.DataUpdateJPanel;
import presentation.guiForDataVisualization.DataVisualizationJPanel;
import presentation.guiForVirtualTrading.VirtualTradingJPanel;

/**
 *
 * @author Dinh
 */
public class mainJFrame extends javax.swing.JFrame {

    /** Creates new form mainJFrame */
    public mainJFrame() {
        initComponents();
        initOtherComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJTabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new mainJFrame().setVisible(true);
            }
        });
    }

    private void initOtherComponents() {
        DataUpdateJPanel dataUpdateJPanel = new DataUpdateJPanel();
        mainJTabbedPane.addTab("Data Update", dataUpdateJPanel);

        VirtualTradingJPanel virtualTradingJPanel = new VirtualTradingJPanel();
        mainJTabbedPane.addTab("Virtual Trading", virtualTradingJPanel);

        DataVisualizationJPanel dataVisualizationJPanel = new DataVisualizationJPanel();
        mainJTabbedPane.addTab("Data Visualization", dataVisualizationJPanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane mainJTabbedPane;
    // End of variables declaration//GEN-END:variables
}
