/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataUpdateJPanel.java
 *
 * Created on Jun 8, 2011, 10:22:49 AM
 */
package presentation.guiForDataUpdate;

import business.dataUpdate.DataGetter.AbstractDataGetter;
import business.dataUpdate.DataProcessor.AbstractDataProcessor;
import business.dataUpdate.UpdateData;
import business.dataUpdate.Utility;
import dataAccess.databaseManagement.manager.PriceManager;

/**
 *
 * @author Dinh
 */
public class DataUpdateJPanel extends javax.swing.JPanel {

    private static PriceManager priceManager = new PriceManager();

    /** Creates new form DataUpdateJPanel */
    public DataUpdateJPanel() {
        initComponents();
        initOtherComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateJButton = new javax.swing.JButton();
        sourceJLabel = new javax.swing.JLabel();
        sourceJComboBox = new javax.swing.JComboBox();
        lastUpdateJLabel = new javax.swing.JLabel();

        updateJButton.setText("Update");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });

        sourceJLabel.setText("Source:");

        sourceJComboBox.setModel(new javax.swing.DefaultComboBoxModel(business.dataUpdate.Utility.ONLINE_RESOURCES));

        lastUpdateJLabel.setText("Last Update:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sourceJLabel)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lastUpdateJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateJButton))
                    .addComponent(sourceJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourceJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastUpdateJLabel)
                    .addComponent(updateJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
        new Thread(new Runnable() {

            @Override
            public void run() {
                lastUpdateJLabel.setText("Updating ....");
                AbstractDataGetter dataGetter = Utility.getDataGetter((String) sourceJComboBox.getSelectedItem());
                AbstractDataProcessor dataProcessor = Utility.getDataProcessor((String) sourceJComboBox.getSelectedItem());
                UpdateData.updateDataFromSpecificDate(priceManager.getLatestDate(), dataGetter, dataProcessor);
                lastUpdateJLabel.setText("Last Update: " + priceManager.getLatestDate().toString());
            }
        }).start();

    }//GEN-LAST:event_updateJButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lastUpdateJLabel;
    private javax.swing.JComboBox sourceJComboBox;
    private javax.swing.JLabel sourceJLabel;
    private javax.swing.JButton updateJButton;
    // End of variables declaration//GEN-END:variables
//    private final JFileChooser fileChooser = new JFileChooser();
//    private File selectedFile = null;

    private void initOtherComponents() {
        lastUpdateJLabel.setText("Last Update: " + priceManager.getLatestDate().toString());
    }
}
