/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DecisionAlgorithmEvaluationJPanel.java
 *
 * Created on Jun 23, 2011, 4:40:37 PM
 */

package presentation.guiForDecisionAlgorithmEvaluation;

import dataAccess.databaseManagement.entity.OrderEntity;
import dataAccess.databaseManagement.entity.PortfolioEntity;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.TreeMap;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import layout.TableLayout;
import presentation.guiForVirtualTrading.PortfolioTableModel;
import presentation.mainJFrame;

/**
 *
 * @author Dinh
 */
public class DecisionAlgorithmEvaluationJPanel extends javax.swing.JPanel {

    /** Creates new form DecisionAlgorithmEvaluationJPanel */
    public DecisionAlgorithmEvaluationJPanel() {
        initComponents();
        initOtherComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateJPanel = new javax.swing.JPanel();
        datejLabel = new javax.swing.JLabel();
        fromDateJLabel = new javax.swing.JLabel();
        toDateJLabel = new javax.swing.JLabel();
        fromDatejSpinner = new javax.swing.JSpinner();
        toDatejSpinner = new javax.swing.JSpinner();
        algorithmjPanel = new javax.swing.JPanel();
        decAlgjLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        decAlgsJList = new javax.swing.JList();
        addDecAlgjButton = new javax.swing.JButton();
        removeDecAlgjButton = new javax.swing.JButton();
        initalPortfolioJPanel = new javax.swing.JPanel();
        initalStatejLabel = new javax.swing.JLabel();
        cashRemainjLabel = new javax.swing.JLabel();
        portfoliojLabel = new javax.swing.JLabel();
        cashRemainjTextField = new javax.swing.JTextField();
        vndjLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        portfolioJTable = new javax.swing.JTable();
        importJButton = new javax.swing.JButton();
        comparisonTableJPanel = new javax.swing.JPanel();
        comparisonTableJLabel = new javax.swing.JLabel();
        tableJPanel = new javax.swing.JPanel();
        refreshJButton = new javax.swing.JButton();
        evaluationCriteriaJPanel = new javax.swing.JPanel();
        decEvaluationCriteriaJLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        decEvaCrisJList = new javax.swing.JList();
        addDecEvaCriteriajButton = new javax.swing.JButton();
        removeDecEvaCriteriajButton = new javax.swing.JButton();

        datejLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        datejLabel.setText("DATE");

        fromDateJLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        fromDateJLabel.setText("From:");

        toDateJLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        toDateJLabel.setText("To:");

        fromDatejSpinner.setModel(new javax.swing.SpinnerDateModel());
        fromDatejSpinner.setEditor(new JSpinner.DateEditor(fromDatejSpinner, "MM/dd/yyyy"));

        toDatejSpinner.setModel(new javax.swing.SpinnerDateModel());
        toDatejSpinner.setEditor(new JSpinner.DateEditor(toDatejSpinner, "MM/dd/yyyy"));

        javax.swing.GroupLayout dateJPanelLayout = new javax.swing.GroupLayout(dateJPanel);
        dateJPanel.setLayout(dateJPanelLayout);
        dateJPanelLayout.setHorizontalGroup(
            dateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateJPanelLayout.createSequentialGroup()
                .addGroup(dateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dateJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(datejLabel))
                    .addGroup(dateJPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(dateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fromDateJLabel)
                            .addComponent(toDateJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(toDatejSpinner)
                            .addComponent(fromDatejSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        dateJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {fromDatejSpinner, toDatejSpinner});

        dateJPanelLayout.setVerticalGroup(
            dateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromDateJLabel)
                    .addComponent(fromDatejSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toDateJLabel)
                    .addComponent(toDatejSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        dateJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {fromDatejSpinner, toDatejSpinner});

        decAlgjLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        decAlgjLabel.setText("DECISION ALGORITHM");

        decAlgsJList.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(decAlgsJList);

        addDecAlgjButton.setText("Add");
        addDecAlgjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDecAlgjButtonActionPerformed(evt);
            }
        });

        removeDecAlgjButton.setText("Remove");
        removeDecAlgjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDecAlgjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout algorithmjPanelLayout = new javax.swing.GroupLayout(algorithmjPanel);
        algorithmjPanel.setLayout(algorithmjPanelLayout);
        algorithmjPanelLayout.setHorizontalGroup(
            algorithmjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(algorithmjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(algorithmjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(algorithmjPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(algorithmjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeDecAlgjButton)
                            .addComponent(addDecAlgjButton)))
                    .addComponent(decAlgjLabel))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        algorithmjPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addDecAlgjButton, removeDecAlgjButton});

        algorithmjPanelLayout.setVerticalGroup(
            algorithmjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(algorithmjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(decAlgjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(algorithmjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(algorithmjPanelLayout.createSequentialGroup()
                        .addComponent(addDecAlgjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeDecAlgjButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        algorithmjPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addDecAlgjButton, removeDecAlgjButton});

        initalStatejLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        initalStatejLabel.setText("INITAL STATE");

        cashRemainjLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        cashRemainjLabel.setText("Cash Remain:");

        portfoliojLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        portfoliojLabel.setText("Portfolio:");

        cashRemainjTextField.setEditable(false);

        vndjLabel.setText("VND");

        portfolioJTable.setModel(new PortfolioTableModel());
        jScrollPane2.setViewportView(portfolioJTable);

        importJButton.setText("Import");
        importJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout initalPortfolioJPanelLayout = new javax.swing.GroupLayout(initalPortfolioJPanel);
        initalPortfolioJPanel.setLayout(initalPortfolioJPanelLayout);
        initalPortfolioJPanelLayout.setHorizontalGroup(
            initalPortfolioJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initalPortfolioJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(initalPortfolioJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(initalStatejLabel)
                    .addGroup(initalPortfolioJPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(initalPortfolioJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(portfoliojLabel)
                            .addGroup(initalPortfolioJPanelLayout.createSequentialGroup()
                                .addComponent(cashRemainjLabel)
                                .addGap(18, 18, 18)
                                .addComponent(cashRemainjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vndjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                                .addComponent(importJButton))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))))
                .addContainerGap())
        );
        initalPortfolioJPanelLayout.setVerticalGroup(
            initalPortfolioJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initalPortfolioJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(initalStatejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(initalPortfolioJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashRemainjLabel)
                    .addComponent(cashRemainjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vndjLabel)
                    .addComponent(importJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(portfoliojLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        comparisonTableJLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        comparisonTableJLabel.setText("COMPARISON TABLE");

        javax.swing.GroupLayout tableJPanelLayout = new javax.swing.GroupLayout(tableJPanel);
        tableJPanel.setLayout(tableJPanelLayout);
        tableJPanelLayout.setHorizontalGroup(
            tableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        tableJPanelLayout.setVerticalGroup(
            tableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout comparisonTableJPanelLayout = new javax.swing.GroupLayout(comparisonTableJPanel);
        comparisonTableJPanel.setLayout(comparisonTableJPanelLayout);
        comparisonTableJPanelLayout.setHorizontalGroup(
            comparisonTableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comparisonTableJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comparisonTableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comparisonTableJPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tableJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(comparisonTableJPanelLayout.createSequentialGroup()
                        .addComponent(comparisonTableJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                        .addComponent(refreshJButton)))
                .addContainerGap())
        );
        comparisonTableJPanelLayout.setVerticalGroup(
            comparisonTableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comparisonTableJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comparisonTableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comparisonTableJLabel)
                    .addComponent(refreshJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        decEvaluationCriteriaJLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        decEvaluationCriteriaJLabel.setText("DECISION EVALUATION CRITERIA");

        decEvaCrisJList.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(decEvaCrisJList);

        addDecEvaCriteriajButton.setText("Add");
        addDecEvaCriteriajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDecEvaCriteriajButtonActionPerformed(evt);
            }
        });

        removeDecEvaCriteriajButton.setText("Remove");
        removeDecEvaCriteriajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDecEvaCriteriajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout evaluationCriteriaJPanelLayout = new javax.swing.GroupLayout(evaluationCriteriaJPanel);
        evaluationCriteriaJPanel.setLayout(evaluationCriteriaJPanelLayout);
        evaluationCriteriaJPanelLayout.setHorizontalGroup(
            evaluationCriteriaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(evaluationCriteriaJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(evaluationCriteriaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(evaluationCriteriaJPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(evaluationCriteriaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addDecEvaCriteriajButton)
                            .addComponent(removeDecEvaCriteriajButton)))
                    .addComponent(decEvaluationCriteriaJLabel))
                .addContainerGap())
        );

        evaluationCriteriaJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addDecEvaCriteriajButton, removeDecEvaCriteriajButton});

        evaluationCriteriaJPanelLayout.setVerticalGroup(
            evaluationCriteriaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(evaluationCriteriaJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(decEvaluationCriteriaJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(evaluationCriteriaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(evaluationCriteriaJPanelLayout.createSequentialGroup()
                        .addComponent(addDecEvaCriteriajButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeDecEvaCriteriajButton))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        evaluationCriteriaJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addDecEvaCriteriajButton, removeDecEvaCriteriajButton});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(algorithmjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(evaluationCriteriaJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(initalPortfolioJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comparisonTableJPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(algorithmjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(evaluationCriteriaJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(initalPortfolioJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comparisonTableJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void importJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importJButtonActionPerformed
        importPortfolioDialog.setVisible(true);
    }//GEN-LAST:event_importJButtonActionPerformed

    private void removeDecAlgjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDecAlgjButtonActionPerformed
        DefaultListModel model = (DefaultListModel) this.decAlgsJList.getModel();
        int[] selectedIndices = decAlgsJList.getSelectedIndices();
        int j = 0;
        for (int i : selectedIndices) {
            model.remove(i-j);
            ++j;
        }
        decAlgsJList.updateUI();
    }//GEN-LAST:event_removeDecAlgjButtonActionPerformed

    private void addDecAlgjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDecAlgjButtonActionPerformed
        addDecAlgDialog.setVisible(true);
        DefaultListModel model = (DefaultListModel) this.decAlgsJList.getModel();
        model.addElement("aaaa");
    }//GEN-LAST:event_addDecAlgjButtonActionPerformed

    private void addDecEvaCriteriajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDecEvaCriteriajButtonActionPerformed
        addCriteriaDialog.setVisible(true);
        DefaultListModel model = (DefaultListModel) this.decEvaCrisJList.getModel();
        model.addElement("aaaa");
    }//GEN-LAST:event_addDecEvaCriteriajButtonActionPerformed

    private void removeDecEvaCriteriajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDecEvaCriteriajButtonActionPerformed
        DefaultListModel model = (DefaultListModel) this.decEvaCrisJList.getModel();
        int[] selectedIndices = decEvaCrisJList.getSelectedIndices();
        int j = 0;
        for (int i : selectedIndices) {
            model.remove(i-j);
            ++j;
        }
        decEvaCrisJList.updateUI();
    }//GEN-LAST:event_removeDecEvaCriteriajButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        updateComparisonTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDecAlgjButton;
    private javax.swing.JButton addDecEvaCriteriajButton;
    private javax.swing.JPanel algorithmjPanel;
    private javax.swing.JLabel cashRemainjLabel;
    private javax.swing.JTextField cashRemainjTextField;
    private javax.swing.JLabel comparisonTableJLabel;
    private javax.swing.JPanel comparisonTableJPanel;
    private javax.swing.JPanel dateJPanel;
    private javax.swing.JLabel datejLabel;
    private javax.swing.JLabel decAlgjLabel;
    private javax.swing.JList decAlgsJList;
    private javax.swing.JList decEvaCrisJList;
    private javax.swing.JLabel decEvaluationCriteriaJLabel;
    private javax.swing.JPanel evaluationCriteriaJPanel;
    private javax.swing.JLabel fromDateJLabel;
    private javax.swing.JSpinner fromDatejSpinner;
    private javax.swing.JButton importJButton;
    private javax.swing.JPanel initalPortfolioJPanel;
    private javax.swing.JLabel initalStatejLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable portfolioJTable;
    private javax.swing.JLabel portfoliojLabel;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton removeDecAlgjButton;
    private javax.swing.JButton removeDecEvaCriteriajButton;
    private javax.swing.JPanel tableJPanel;
    private javax.swing.JLabel toDateJLabel;
    private javax.swing.JSpinner toDatejSpinner;
    private javax.swing.JLabel vndjLabel;
    // End of variables declaration//GEN-END:variables

    private JDialog importPortfolioDialog = newImportPortfolioJDialog();
    private JDialog addDecAlgDialog = newAddDecAlgJDialog();
    private JDialog addCriteriaDialog = newAddCriteriaJDialog();

    private JDialog newAddDecAlgJDialog() {
        JDialog jDialog = new JDialog(mainJFrame.mainFrame, true);
        AddNewDecAlgJPanel panel = new AddNewDecAlgJPanel(jDialog);
        jDialog.add(panel);
        jDialog.pack();
        return jDialog;
    }

    public JDialog newImportPortfolioJDialog() {
        JDialog jDialog = new JDialog(mainJFrame.mainFrame, true);
        ImportPortfolioJPanel panel = new ImportPortfolioJPanel(jDialog);
        jDialog.add(panel);
        jDialog.pack();
        return jDialog;
    }

    private JDialog newAddCriteriaJDialog() {
        JDialog jDialog = new JDialog(mainJFrame.mainFrame, true);
        AddNewDecEvaCriteriaJPanel panel = new AddNewDecEvaCriteriaJPanel(jDialog);
        jDialog.add(panel);
        jDialog.pack();
        return jDialog;
    }

    private void initOtherComponents() {
        Calendar now = Calendar.getInstance();
        toDatejSpinner.setValue(now.getTime());
        now.add(Calendar.MONTH, -6);
        fromDatejSpinner.setValue(now.getTime());
    }

    private void updateComparisonTable() {

        //create table layout
        double size[][] = new double[2][];
        size[0] = new double[decEvaCrisJList.getModel().getSize() + 1];
        for (int i = 0; i < size[0].length; ++i) {
            size[0][i] = TableLayout.PREFERRED;
        }

        size[1] = new double[decAlgsJList.getModel().getSize() + 1];
        for (int i = 0; i < size[1].length; ++i) {
            size[1][i] = TableLayout.PREFERRED;
        }

        tableJPanel.removeAll();
        tableJPanel.setLayout(new TableLayout(size));

        //add components
        for (int i = 1; i < size[0].length; ++i) {
            JLabel jLabel = new JLabel(decEvaCrisJList.getModel().getElementAt(i-1).toString());
            jLabel.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            tableJPanel.add(jLabel, i +", 0");
        }

        for (int i = 1; i < size[1].length; ++i) {
            RowHeaderJPanel rowHeaderJPanel = new RowHeaderJPanel(decAlgsJList.getModel().getElementAt(i-1), new ArrayList<OrderEntity>(), new ArrayList<PortfolioEntity>());
            rowHeaderJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            tableJPanel.add(rowHeaderJPanel, "0, " + i);
        }

        for (int criteriaIndex = 0; criteriaIndex < size[0].length - 1; ++criteriaIndex) {
            for (int algIndex = 0; algIndex < size[1].length - 1; ++algIndex) {
                TreeMap<String, Object> output = new TreeMap<String, Object>();
                output.put("Lenght", new Long(123));
                output.put("Name", "Dinh");
                CriteriaOutputJPanel criteriaOutputJPanel = new CriteriaOutputJPanel(output);
                criteriaOutputJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                tableJPanel.add(criteriaOutputJPanel, (criteriaIndex + 1) + ", " + (algIndex + 1));
            }
        }

        tableJPanel.updateUI();
    }
}
